### ISSUE TITLE
Could you provide some examples? :)

### ISSUE THREAD

**Issue by DcFamas** [RapierXbox/ShellyElevate#1]
Hey there,
I want to buy and test the Shelly Wall Display with ShellyElevate. Unfortunately I don't know how the handling is right now. Does it work really good? Could you maybe provide some pictures of the finished Shelly? Thanks and best regards :)

**Comment by RapierXbox** [comment]
Yeah, sorry that I read your issue just now... I can take some pictures tomorrow.

**Comment by RapierXbox** [comment]
Here is it in Home Assistant: 
![image](https://github.com/user-attachments/assets/669c2568-076a-44a2-9a5e-785db516defd)

**Comment by NoUsername10** [comment]
Hi, great work.
Could you add pictures of the display running HA also if possible?

**Comment by RapierXbox** [comment]
https://github.com/user-attachments/assets/dfbf606d-deba-43f9-ac13-08e8eea46190 Here you go. You can hear the relay clicking.

**Comment by DcFamas** [comment]
Great, thank you! :)
Will buy one and test and give some feedback.
