### ISSUE TITLE
UART 5V or 3.3V ?

### ISSUE THREAD

**Issue by andrestu** [RapierXbox/ShellyElevate#2]
For the USB2UART adapter: Is possible to specify if the UART (TX/RX pins)  shall be 3.3 or 5 Volt?
I think 3.3 is the correct ones:
![Cattura](https://github.com/user-attachments/assets/01def83d-a942-4702-a9f3-c2b0329b84d9)

many thanks !

**Comment by RapierXbox** [comment]
I was using 5v as I am powering the Wall display the way its powerd by the original powersupply. If I would power the pcb directly I would use 1.8 or 3.3v but the 5v goes trough the voltage regulators on the wall display.

**Comment by RapierXbox** [comment]
So when powering it trough the daughter board use 5v.

**Comment by Habbie** [comment]
I just measured my soldered UART wires, they are 1.8V. I know I used 3.3V to enable adb, but clearly 1.8 is the right voltage.
