### ISSUE TITLE
Wrong connections in usb2uart photo

### ISSUE THREAD

**Issue by andrestu** [RapierXbox/ShellyElevate#3]
The 3.3 and RX signals appear to be reversed in this photo:
![334913695-af3a176d-3b8d-4a5e-9afe-1b01265e4920](https://github.com/user-attachments/assets/705da337-f7a2-4915-878a-4c077e42c748)
It would be useful to put a note about this.
In the next few days I will try to follow your beautiful guide and I can send you a new photo.
thanks a lot

**Comment by RapierXbox** [comment]
Thanks... the setup in the picture was after I was done hacking and not my actual setup. Just the one for the picture. I already have written it in the readme and maby I will take another picture too.
