### ISSUE TITLE
Manually set the address to find Homeassistant

### ISSUE THREAD

**Issue by PantheraIgnis** [RapierXbox/ShellyElevate#5]
Would it be possible to include a way to manually set up the address of the home assistant instance? It doesnt seem to be able to locate one that is in a different VLAN with firewall rules in place

**Comment by RapierXbox** [comment]
I understand that it’s not very user-friendly at the moment, but I assume you can build your own Android app since you’re familiar with VLANs (though that might not be the most logical assumption, haha).

To make this adjustment, just replace line 18 in BootReceiver with the following code:
```String url = "http://yourip:8123";
Uri uri = Uri.parse(url);
Intent browserIntent = new Intent(Intent.ACTION_VIEW, uri);
browserIntent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
browserIntent.setPackage("com.android.chrome");
browserIntent.putExtra("android.support.customtabs.extra.TITLE_VISIBILITY", 0);
browserIntent.putExtra("android.support.customtabs.extra.TINT_ACTION_BUTTON", false);
context.startActivity(browserIntent);
```
